name: 🚀 Release
on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/commit-analyzer@8.0.1
            @semantic-release/release-notes-generator@9.0.3
            @semantic-release/changelog@5.0.1
            @semantic-release/github@7.2.3
            @semantic-release/git@9.0.0
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main', 
              'next', 
              'next-major', 
              {
                name: 'beta', 
                prerelease: true
              }, 
              {
                name: 'alpha', 
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
